Pin to commit for release Release 1.5.0
As previously this was following HEAD and a more recent commit
broke the build with the following error

/openipc-firmware/output/per-package/aws-webrtc/host/opt/ext-toolchain/bin/../lib/gcc/mipsel-openipc-linux-musl/12.3.0/../../../../mipsel-openipc-linux-musl/bin/ld: /data_drive/omlet/openipc-firmware/output/per-package/aws-webrtc/host/mipsel-buildroot-linux-musl/sysroot/usr/lib/libkvsCommonLws.so: undefined reference to `GMTIME_THREAD_SAFE'

Signed-off-by: Alex J Lennon <ajlennon@dynamicdevices.co.uk>